### ISSUE TITLE
Teste de issues

### ISSUE THREAD

**Issue by ulissesfalcao** [falcaodeveloper/Formatacao-de-texto-em-HTML5#1]
Boa tarde,

Isso é apenas **um teste**

[Formatacao-de-texto-em-HTML5](https://github.com/falcaodeveloper/Formatacao-de-texto-em-HTML5)

**Comment by falcaodeveloper** [comment]
Boa tarde Ulisses.

Teste confirmado
*

**Comment by ulissesfalcao** [comment]
ok

**Comment by ulissesfalcao** [comment]
ok

**Comment by falcaodeveloper** [comment]
encerrarei agora
